//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailRequest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmailRequest.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @media only screen and (min-width: 550px) {
        ///            h2 {
        ///                font-size: 18px;
        ///            }
        ///            p {
        ///                font-size: 14px;
        ///            }
        ///            h5 {
        ///                font-size: 16px;
        ///            }
        ///        }
        ///        @media only screen and (max-width: 550px) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttendanceApplied {
            get {
                return ResourceManager.GetString("AttendanceApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @media only screen and (min-width: 550px) {
        ///            h2 {
        ///                font-size: 18px;
        ///            }
        ///            p {
        ///                font-size: 14px;
        ///            }
        ///            h5 {
        ///                font-size: 16px;
        ///            }
        ///        }
        ///        @media only screen and (max-width: 550px) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonException {
            get {
                return ResourceManager.GetString("CommonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @media only screen and (min-width: 550px) {
        ///            h2 {
        ///                font-size: 18px;
        ///            }
        ///            p {
        ///                font-size: 14px;
        ///            }
        ///            h5 {
        ///                font-size: 16px;
        ///            }
        ///        }
        ///        @media only screen and (max-width: 550px) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DailyNotification {
            get {
                return ResourceManager.GetString("DailyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @media only screen and (min-width: 550px) {
        ///            h2 {
        ///                font-size: 18px;
        ///            }
        ///            p {
        ///                font-size: 14px;
        ///            }
        ///            h5 {
        ///                font-size: 16px;
        ///            }
        ///        }
        ///        @media only screen and (max-width: 550px) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmployeeBill {
            get {
                return ResourceManager.GetString("EmployeeBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @media only screen and (min-width: 550px) {
        ///            h2 {
        ///                font-size: 18px;
        ///            }
        ///            p {
        ///                font-size: 14px;
        ///            }
        ///            h5 {
        ///                font-size: 16px;
        ///            }
        ///        }
        ///        @media only screen and (max-width: 550px) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @media only screen and (min-width: 550px) {
        ///            h2 {
        ///                font-size: 18px;
        ///            }
        ///            p {
        ///                font-size: 14px;
        ///            }
        ///            h5 {
        ///                font-size: 16px;
        ///            }
        ///        }
        ///        @media only screen and (max-width: 550px) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LeaveApplied {
            get {
                return ResourceManager.GetString("LeaveApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @media only screen and (min-width: 550px) {
        ///            h2 {
        ///                font-size: 18px;
        ///            }
        ///            p {
        ///                font-size: 14px;
        ///            }
        ///            h5 {
        ///                font-size: 16px;
        ///            }
        ///        }
        ///        @media only screen and (max-width: 550px) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Email Template&lt;/title&gt;
        ///    &lt;style&gt;
        ///        @media only screen and (min-width: 550px) {
        ///            h2 {
        ///                font-size: 18px;
        ///            }
        ///            p {
        ///                font-size: 14px;
        ///            }
        ///            h5 {
        ///                font-size: 16px;
        ///            }
        ///        }
        ///        @media only screen and (max-width: 550px) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimesheetApplied {
            get {
                return ResourceManager.GetString("TimesheetApplied", resourceCulture);
            }
        }
    }
}
